atom_types:
- Ge
- Sb
- Te
generate_features: true
preprocess: true
train_model: true
neural_network:
  pca: true
  pca_whiten: true
#  dropout: 0.5
  weight_initializer:
    type: he normal  
  save_criteria: []
  batch_size: 20
  continue: false
  double_precision: true
  energy_coeff: 1.0
  force_coeff:  0.1
#  normal_stress_coeff: 0.000001
#  shear_stress_coeff:  0.000001
  full_batch: false
  cache: false
  learning_rate: 0.0001
#    decay_rate: 0.95
#    decay_steps: 10000
#    learning_rate: 0.01
#    staircase: true
  loss_scale: 1.0
  acti_func: tanh
  method: Adam
  nodes: 30-30
  optimizer: {}
  print_structure_rmse: true
  regularization:
    type: l2
    params:
      coeff: 1.0e-8
  save_interval: 200
  show_interval: 200
  test: false
  total_iteration: 100000
  train: true
  use_force: true
  use_stress: true
  intra_op_parallelism_threads: 20
  inter_op_parallelism_threads: 2
symmetry_function:
#  atomic_weights:
#    type: gdf
#    params:
#     sigma: 0.07
#  weight_modifier:
#    type: modified sigmoid
#    params:
#     Sb:
#       b: 1.0
#       c: 100.0
#     Te:
#       b: 1.0
#       c: 150.0
  compress_outcar: true
  data_per_tfrecord: 6000
  num_parallel_calls: 40
  params:
    Ge: params_Ge
    Sb: params_Sb
    Te: params_Te
  remain_pickle: true
  valid_rate: 0.1
#  scale_type: uniform gas
#  scale_rho:
#    Ag: 0.0367
#    Au: 0.0285
#    F: 0.06
